name: "fail"
version: "0.1.0"
usage: "fix the pending status"
description: "fix the pending status"
command: "$HELM_PLUGIN_DIR/bin/fail"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"